"""added logging table

Revision ID: 785aac9f0a7d
Revises: bc723ce0d1a3
Create Date: 2024-11-22 11:45:38.203350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785aac9f0a7d'
down_revision = 'bc723ce0d1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=False),
    sa.Column('latest_login', sa.DateTime(), nullable=True),
    sa.Column('previous_login', sa.DateTime(), nullable=True),
    sa.Column('latest_ip', sa.String(), nullable=True),
    sa.Column('previous_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name=op.f('fk_logs_userid_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('(TRUE)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(TRUE)'))

    op.drop_table('logs')
    # ### end Alembic commands ###
