"""empty message

Revision ID: 84ddbaca0a14
Revises: 785aac9f0a7d
Create Date: 2024-11-22 12:09:22.720774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ddbaca0a14'
down_revision = '785aac9f0a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('reg_time', sa.DateTime(), nullable=False),
    sa.Column('latest_login', sa.DateTime(), nullable=True),
    sa.Column('previous_login', sa.DateTime(), nullable=True),
    sa.Column('latest_ip', sa.String(), nullable=True),
    sa.Column('previous_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name=op.f('fk_log_userid_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log'))
    )
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userid', sa.INTEGER(), nullable=False),
    sa.Column('reg_time', sa.DATETIME(), nullable=False),
    sa.Column('latest_login', sa.DATETIME(), nullable=True),
    sa.Column('previous_login', sa.DATETIME(), nullable=True),
    sa.Column('latest_ip', sa.VARCHAR(), nullable=True),
    sa.Column('previous_ip', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name='fk_logs_userid_users'),
    sa.PrimaryKeyConstraint('id', name='pk_logs')
    )
    op.drop_table('log')
    # ### end Alembic commands ###
